name: Changesets

# Pnpm setup based on https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time

on:
  push:
    branches: ["main"]
env:
  CI: true

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # OIDC for npm Trusted Publishing
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=24.0.0"
          check-latest: true
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Restore Turborepo cache
        id: cache-turborepo-restore
        uses: actions/cache/restore@v4
        with:
          # Using SHA will usually provide cache hit on subsequent commits in a PR
          # but will not provide cache hits between PRs, meaning the first run of a PR
          # will usually only be cache misses.
          key: ${{ runner.os }}-turbo-${{ github.sha }}-changeset
          restore-keys: |
            ${{ runner.os }}-turbo-${{ github.sha }}
            ${{ runner.os }}-turbo--changeset
            ${{ runner.os }}-turbo-
          path: .turbo

      - name: Build packages
        run: pnpm build-pkg

      - name: Save Turborepo cache
        id: cache-turborepo-save
        if: always() && steps.cache-turborepo-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.cache-turborepo-restore.outputs.cache-primary-key }}
          path: .turbo

      - name: Create release Pull Request or publish to NPM
        uses: changesets/action@v1
        with:
          commit: "ci(changesets): version packages"
          title: "Changeset: New Version"
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm publish-pkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
